module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      keyframes: {
        slideDown: { '0%': { opacity: '0', transform: 'translateY(-10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(10px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'glow-pulse': { '0%, 100%': { boxShadow: '0 0 0 0 rgba(14,165,233,0)' }, '50%': { boxShadow: '0 0 0 6px rgba(14,165,233,0.15)' } },
        'number-pop': { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.12)' }, '100%': { transform: 'scale(1)' } },
        'status-pulse': { '0%, 100%': { boxShadow: '0 0 0 0 rgba(239,68,68,0)' }, '50%': { boxShadow: '0 0 0 4px rgba(239,68,68,0.35)' } },
        'confetti-fall': { '0%': { transform: 'translateY(-10vh) rotate(0deg)', opacity: '1' }, '100%': { transform: 'translateY(110vh) rotate(360deg)', opacity: '0.3' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'ring-grow': { '0%': { transform: 'scale(0.8)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'page-enter': { '0%': { opacity: '0', transform: 'translateY(6px) scale(0.995)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
      },
      animation: {
        'slide-down': 'slideDown 0.25s ease-out',
        'slide-up': 'slideUp 0.25s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'number-pop': 'number-pop 0.35s ease-out',
        'status-pulse': 'status-pulse 1.2s ease-in-out infinite',
        'confetti-fall': 'confetti-fall 1.4s ease-in forwards',
        shimmer: 'shimmer 2s linear infinite',
        'ring-grow': 'ring-grow 0.3s ease-out',
        'page-enter': 'page-enter 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
};